<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih Bank_bank-VABCA</name>
   <tag></tag>
   <elementGuidId>e79da1f9-4dfd-4fc9-83b0-9f309b32cd4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bank-VABCA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bank-VABCA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf2eccd3-d4cf-4c9e-ae00-05e6b49aaff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6d852fcd-3f51-4b57-8d27-7bd7c9759b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank-VABCA</value>
      <webElementGuid>49044c59-400a-46ed-a435-b313335bb052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 absolute h-8 w-8 left-0</value>
      <webElementGuid>cf7abc34-471d-498d-a87d-7ce40a6b8a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>radio-bank-VABCA</value>
      <webElementGuid>03e96354-4c7e-402b-bd72-1d47c4f9c18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VABCA</value>
      <webElementGuid>d3057843-3a8f-4186-874f-13d8966ce22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bank-VABCA&quot;)</value>
      <webElementGuid>b5870667-269f-404b-ba2c-26ba29c6351f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bank-VABCA']</value>
      <webElementGuid>a803ce37-13f0-4f03-80b1-9d68609d7c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/main/section/div/div[3]/div[2]/ul/div/li/div/div/input</value>
      <webElementGuid>35c096fe-d353-48c1-98d1-857e2b597194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b60271a6-e2c7-43f7-97ad-1024d4f5ecdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'bank-VABCA']</value>
      <webElementGuid>3c6949af-5a89-46e8-aca6-59b2c087d6c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
