<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hingga 23 Apr 2023Batalkan</name>
   <tag></tag>
   <elementGuidId>83721fb0-5d5c-4406-86d1-c4eaa33a0c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ticket-separator.flex.justify-between.items-center.py-4.px-5.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>892380af-5d6b-41e9-a27c-7a7a08419578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ticket-separator flex justify-between items-center py-4 px-5 active</value>
      <webElementGuid>0e09168b-ceb6-4828-9161-a3c5dbd05cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hingga 23 Apr 2023Batalkan</value>
      <webElementGuid>a9525dc1-cec3-4db4-8c9c-2ad4a71d1a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none w-1-3&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap bg-neutral-900&quot;]/div[@class=&quot;px-4 pt-4&quot;]/div[@class=&quot;overflow-y-auto md:h-90 pb-12 md:pb-0&quot;]/div[@class=&quot;ticket rounded mb-4 active&quot;]/div[1]/div[@class=&quot;ticket-separator flex justify-between items-center py-4 px-5 active&quot;]</value>
      <webElementGuid>1043e037-7cbf-4f7d-94a2-de979be5e250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>0cda9400-3ab2-4011-9250-68f07fc922af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo BNI Ramadan'])[1]/following::div[2]</value>
      <webElementGuid>19b545a0-dec3-4004-bff5-2646d02bef5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pakai Voucher'])[1]/following::div[15]</value>
      <webElementGuid>fe5d8c78-f58b-464a-a46c-e62a5c986d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>07478e94-5e87-46c3-a962-9325e51c20cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hingga 23 Apr 2023Batalkan' or . = 'Hingga 23 Apr 2023Batalkan')]</value>
      <webElementGuid>c0461fbf-36f6-4212-b334-df1044b22853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
