<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>2482af07-a3fc-4495-bb4e-b6ca190c7f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060d831a-2fc1-410f-9f64-96116c7dc82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>389be025-5812-4b64-a3c2-20d83313668e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2</value>
      <webElementGuid>3b6b1e8a-9c02-4359-8fda-262e59a81b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2d5d274a-7deb-4050-a1c1-fbdfa50de4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-md bg-neutral-900&quot;]/div[@class=&quot;login-form-container&quot;]/div[@class=&quot;mx-auto my-0 text-neutral-200 login-form-popup p-3&quot;]/form[1]/div[@class=&quot;mb-5&quot;]/div[1]/fieldset[@class=&quot;text-input border-none relative p-0 qa-password-field&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 gap-2 pl-4 pr-2&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>3efa8c09-64c1-415a-adf4-ca99eccfc28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>c9ffca6b-6c2a-4a6d-9727-66e106332e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>691b8adb-0675-4006-99d9-6b1981d351b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div/form/div/div/fieldset/div/div/input</value>
      <webElementGuid>30129387-32b1-4ff5-8871-8eff3c921308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/fieldset/div/div/input</value>
      <webElementGuid>95e0ad19-e2f7-4c84-9a45-5bb7564c26a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>053e5f83-b969-4ca2-937f-88504971b334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'text']</value>
      <webElementGuid>fb54ef24-7973-40b8-a688-c5ca4b01ecd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
