<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmailNo.Handphone_username</name>
   <tag></tag>
   <elementGuidId>b709064c-d57c-4de4-a1bb-4e6b1b97f269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0751f358-b080-41cd-9c53-497cfd737f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>38c4404c-61b1-4d85-ad3f-505525d7c484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2</value>
      <webElementGuid>c5652909-518d-4f38-9b45-c55846f7592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-md bg-neutral-900&quot;]/div[@class=&quot;login-form-container&quot;]/div[@class=&quot;mx-auto my-0 text-neutral-200 login-form-popup p-3&quot;]/form[1]/div[@class=&quot;mb-5&quot;]/fieldset[@class=&quot;text-input border-none relative p-0 mb-2 qa-email-phone-field&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 pl-4 pr-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>205dc9fa-1f9c-4afe-bad3-c361e566b859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>8f6e2e5d-a427-42fa-822a-baff24fcd0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>343fda4c-e373-41b1-adba-222ac5bb0395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/fieldset/div/div/input</value>
      <webElementGuid>2bdea632-b208-4253-9259-57ca6faae1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>aad4c723-9275-4e82-9ff1-41615159d661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
