<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Gunakan</name>
   <tag></tag>
   <elementGuidId>e1d7bc67-6ade-4d1e-bba4-0b3e2ca75d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div/div/div[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mw-ripple-effect.btn.rounded.text-sm.relative.overflow-hidden.w-full.btn-filled.text-neutral-1000.bg-primary-1.font-medium.tracking-wider.w-full.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2af17826-68d7-4ab3-8b36-02819ab46c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-ripple-effect btn rounded text-sm relative overflow-hidden w-full btn-filled text-neutral-1000 bg-primary-1 font-medium tracking-wider w-full uppercase</value>
      <webElementGuid>4503c22e-b0fe-43db-bc02-46dd9c08a56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gunakan</value>
      <webElementGuid>8373f828-ef7a-44ed-97fe-0b4d048d9ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none w-1-3&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap bg-neutral-900&quot;]/div[4]/div[@class=&quot;p-4 bg-neutral-800 rounded-b-2&quot;]/button[@class=&quot;mw-ripple-effect btn rounded text-sm relative overflow-hidden w-full btn-filled text-neutral-1000 bg-primary-1 font-medium tracking-wider w-full uppercase&quot;]</value>
      <webElementGuid>a7b8c05a-f70c-406e-b3dd-a6954095421e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div[4]/div/button</value>
      <webElementGuid>ff43d6a8-89e7-4168-bc8a-7c17bddbb316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user'])[2]/following::button[1]</value>
      <webElementGuid>899dfd3f-7795-4cee-9654-e99f6daf44ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='voucher'])[4]/following::button[1]</value>
      <webElementGuid>36eff2ab-c2c4-410b-8902-daa012c6a3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>d40a48c9-3cb4-4aec-aba1-34b64d2c6f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>cca0fbe2-2766-4f96-a6fc-4175da39308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gunakan']/parent::*</value>
      <webElementGuid>78883cc1-a3ff-4cb0-a77a-3788ef7e9892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>be9409ae-a21f-4248-ae9d-0d7ea9e68db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Gunakan' or . = 'Gunakan')]</value>
      <webElementGuid>813b6e21-a5aa-471e-8d38-737572121a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher tidak bisa digabungkan dengan promo atau voucher lainnya.'])[1]/following::button[1]</value>
      <webElementGuid>87831220-c991-424d-80e6-486c01d43612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher hanya berlaku untuk 1 (satu) kali transaksi bagi 1 user.'])[1]/following::button[1]</value>
      <webElementGuid>934f6ba0-fad5-4fb4-9d50-6c363441d5b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
